# Generated by Django 5.0.3 on 2024-03-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('brand_name', models.CharField(max_length=50, null=True)),
                ('average_price', models.PositiveBigIntegerField(blank=True, default=0)),
            ],
        ),
    ]
