# Generated by Django 5.0.3 on 2024-03-13 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('average_price', models.PositiveBigIntegerField(blank=True, default=0)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='car_prices.brands', verbose_name='Marca')),
            ],
        ),
        migrations.DeleteModel(
            name='CarInfo',
        ),
    ]
