# Generated by Django 5.0.3 on 2024-03-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_prices', '0003_rename_brand_name_brands_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
