# Generated by Django 5.0.3 on 2024-03-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_prices', '0002_brands_modelinfo_delete_carinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='brand_name',
            new_name='name',
        ),
    ]
